# Generated by Django 4.2.9 on 2024-01-11 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('m_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Role',
        ),
    ]
