# Generated by Django 4.2.9 on 2024-01-12 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('m_app', '0002_demo'),
    ]

    operations = [
        migrations.AddField(
            model_name='test3',
            name='testing4',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
