# Generated by Django 5.0.1 on 2024-01-12 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('m_app', '0002_demo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='demo',
            old_name='emp_name',
            new_name='demo1',
        ),
    ]
