# Generated by Django 5.0.1 on 2024-01-11 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('m_app', '0003_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name1', models.CharField(max_length=100)),
            ],
        ),
    ]
