# Generated by Django 5.0.1 on 2024-01-12 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('m_app', '0004_rename_emp_name_demo_demo1'),
    ]

    operations = [
        migrations.AddField(
            model_name='demo',
            name='demo2',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
