# Generated by Django 5.0.1 on 2024-01-11 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('m_app', '0004_role1'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name2', models.CharField(max_length=100)),
            ],
        ),
    ]
