# Generated by Django 4.2.9 on 2024-01-11 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('m_app', '0004_role1'),
    ]

    operations = [
        migrations.RenameField(
            model_name='role',
            old_name='name',
            new_name='namee',
        ),
    ]
