# Generated by Django 4.2.9 on 2024-01-12 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('m_app', '0003_test3_testing4'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='st_name',
            new_name='st_namee',
        ),
    ]
