# Generated by Django 4.2.9 on 2024-01-11 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('m_app', '0005_rename_name_role_namee'),
        ('m_app', '0005_role2'),
    ]

    operations = [
    ]
